name: cleany_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  http: ^1.4.0
  provider: ^6.1.5
  flutter_secure_storage: ^9.2.4
  intl: 0.20.2
  pin_code_fields: ^8.0.1
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  path: ^1.9.1
  mime: ^2.0.0
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0
  path_provider: ^2.1.5
  image: ^4.5.4
  http_parser: ^4.0.2
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900